server:
    interface-automatic: yes
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow
    access-control: fd00::/8 allow
    access-control: fe80::/10 allow
    module-config: "respip validator iterator"
    tls-system-cert: yes
    serve-expired: yes
    infra-keep-probing: yes

rpz:
    name: allowlist
    zonefile: /etc/unbound/allowlist.rpz

rpz:
    name: blocklist
    url: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/light.txt
    zonefile: /var/lib/unbound/blocklist.rpz
    rpz-log: yes
